# Generated by Django 5.1.1 on 2024-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.food4fuel.com%2Fproduct%2F21-day-plan-delivery%2F&psig=AOvVaw1tXaIRJvh0_1fZiQJiklO1&ust=1728995026476000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMju6MnujYkDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
